name: Discord Bot

on:
  push:
    branches:
      - mind  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your desired Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Change this to the actual requirements file name

    - name: Run Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python main.py # Change this to the actual path of your bot script
